feat: add readme for samples
apache/dubbo-go-samples pull request #52
Opened 2021-02-23 07:24 UTC by yakecanlee

add readme for generic, helloworld, group and rest.

2021-03-03 14:31 UTC, beiwei30 commented on general/rest/go-client/cmd/client.go
> +	"github.com/apache/dubbo-go-samples/general/rest/go-client/pkg"
pls. group the import

2021-03-03 14:34 UTC, beiwei30 requested changes

2021-03-03 14:34 UTC, beiwei30 commented on general/rest/go-server/cmd/server.go
> +	_ "github.com/apache/dubbo-go-samples/general/rest/go-server/pkg"
pls. group the imports.

2021-03-03 14:34 UTC, beiwei30 commented
@yakecanlee pls. check my review comments.

2021-03-03 14:55 UTC, yakecanlee commented
> @yakecanlee pls. check my review comments.

done. pls review.

2021-03-04 15:42 UTC, AlexStocks commented on group/go-client/pkg/user.go
> +	Id   string
using ID pls.

2021-03-04 15:42 UTC, AlexStocks commented on group/go-server-group-a/cmd/server.go
> +	"github.com/apache/dubbo-go-samples/group/go-server-group-a/pkg"
move this pkg to another import block as the 3rd import group.

2021-03-04 15:44 UTC, AlexStocks commented on group/go-server-group-a/pkg/user.go
> +	hessian "github.com/apache/dubbo-go-hessian2"
the two pkgs should be placed into the 2rd import group because they are not belongs to "github.com/apache/dubbo-go-samples".

2021-03-04 15:45 UTC, AlexStocks commented on group/go-server-group-a/tests/integration/main_test.go
> +import (
move it above as the 1st import group.

2021-03-04 15:46 UTC, AlexStocks commented on group/go-server-group-b/cmd/server.go
> +	"github.com/apache/dubbo-go-samples/group/go-server-group-b/pkg"
move it out to another import block as the 3rd import group.

2021-03-04 15:47 UTC, AlexStocks commented on group/go-server-group-b/pkg/user.go
> +import (
merge it to the 2rd import group.

2021-03-04 15:48 UTC, AlexStocks commented on group/go-server-group-b/tests/integration/main_test.go
> +import (
move it above as the 1st import group.

2021-03-04 15:48 UTC, AlexStocks commented on group/go-server-group-b/tests/integration/main_test.go
> +	Id   string
Id -> ID

2021-03-04 15:49 UTC, AlexStocks commented on group/go-server-group-b/tests/integration/userprovider_test.go
> +import (
add a blank line above to split the two import blocks.

2021-03-04 15:49 UTC, AlexStocks commented on helloworld/README.md
> +	Id   string
Id -> ID

2021-03-04 15:49 UTC, AlexStocks commented on helloworld/README.md
> +	Id   string
Id -> ID

2021-03-04 15:50 UTC, AlexStocks commented on helloworld/README_zh.md
> +	Id   string
Id -> ID

2021-03-04 15:50 UTC, AlexStocks commented on helloworld/README_zh.md
> +	Id   string
Id -> ID

2021-03-05 09:49 UTC, beiwei30 approved these changes
LGTM now.

2021-03-08 06:14 UTC, zouyx reviewed
make checking success pls

2021-03-11 08:37 UTC, zouyx reviewed
fix conflicts pls

2021-03-11 08:47 UTC, yakecanlee commented
> fix conflicts pls

i can merge this branch into master without conflicts 😂

> fix conflicts pls

done

2021-03-11 08:47 UTC, yakecanlee commented
> fix conflicts pls

done

2021-03-11 11:23 UTC, AlexStocks approved these changes

2021-03-11 11:25 UTC, LaurenceLiZhixin approved these changes

2021-03-11 13:39 UTC, merged