add: direct README
apache/dubbo-go-samples pull request #59
Opened 2021-03-05 13:54 UTC by PhilYue

2021-03-05 14:35 UTC, AlexStocks commented on direct/README.md
> +### 目录
hey, guy, pls translate the chinese into english.

2021-03-05 14:58 UTC, AlexStocks commented on direct/README.md
> +```yaml
pls add a blank line btw line 30 and line 31

2021-03-05 15:00 UTC, AlexStocks commented on direct/README.md
> +2. Startup: Direct connection to the service to complete a service call
add a blank line above line 117 and lint 118

2021-03-05 15:27 UTC, beiwei30 requested changes

2021-03-05 15:27 UTC, beiwei30 commented on direct/go-client/conf/client.yml
> +#protocol_conf:
don't comment out, if it's unnessary, simply remove it.

2021-03-05 15:37 UTC, AlexStocks approved these changes

2021-03-06 07:04 UTC, LaurenceLiZhixin approved these changes

2021-03-06 07:14 UTC, LaurenceLiZhixin approved these changes

2021-03-08 06:16 UTC, zouyx approved these changes

2021-03-08 11:08 UTC, merged